### ISSUE TITLE
Other people being able to join your server

### ISSUE THREAD

**Issue by MartinDevelopment** [themoonisacheese/2bored2wait#18]
Currently other people are able to connect to your server if they have the ip and port(since online-mode: false) and play as your account. You are able to do this even without using the correct username. To solve this I recommend putting online-mode to true and adding a whitelist.

**Comment by themoonisacheese** [comment]
I can't set online-mode to true because starting the queue revokes your minecraft login token. A whitelist could indeed be used, but it wouldn't be a good solution because it would just require the malicious person to know your username as well (because no online mode).

I have honestly no idea how to protect this short of featuring a password/login system in the minecraft server (much like online-mode:false servers often have a /login plugin), but this is no easy task.

Until this is done, the most efficient protection would be to use a different port than 25565.

**Comment by MartinDevelopment** [comment]
The queue revoking your minecraft login token isn't a large issue since all you have to do is relog your minecraft account in the launcher and everything will work fine. This is because a valid token is no longer needed the moment the proxy joins the queue.

**Comment by themoonisacheese** [comment]
I just looked into it, and i'm afraid minecraft-protocol, which is responsible for creating the server, doesn't support whitelists. I think making the server asking for the password on login is easier than implementing a whitelist, and it should also provide a better user experience by not requiring you to relog every time you enter the queue.

**Comment by viluzi** [comment]
if someone else joins through your proxy server does it let them into your account or theirs

**Comment by themoonisacheese** [comment]
your account,

**Comment by viluzi** [comment]
is there a way to add a password system or something with minecraft-protocol
probably not..

**Comment by themoonisacheese** [comment]
there's always a way, but i have to actually do it, and i've got exams.

**Comment by MartinDevelopment** [comment]
I created a temporary fix here: https://github.com/MartinDevelopment/2bored2wait/tree/patch-2
What this does is putting online-mode to true, which requires users to relog in the launcher to regain a valid authentication token. It also shuts down the server whenever someone with the incorrect username joins (a.k.a stopping the queue). I know this is not optimal, but it is the only solution I could find that only took a couple seconds to write. (I don't have much time)

**Comment by laurinneff** [comment]
I know this is late, but couldn't you also just listen on 127.0.0.1 instead of 0.0.0.0, only allowing local connections?

**Comment by sijanec** [comment]
yeah, I made that possible to set in config.json (see my fork https://github.com/sijanec/2bored2wait). 
And then you create a ssh tunnel or a VPN from your server where 2b2w is hosted to your PC where you play.

**Comment by viluzi** [comment]
make a ip whitelist. Obvious solution. If connecting from new ip just dont allow it.

**Comment by sijanec** [comment]
Or a username whitelist (the username is a secret). This may be easier to
implement and use in case of proxied connections or
server-side-request-forgery.

V V čet., 9. jul. 2020 ob 21:20 je oseba viluzi <notifications@github.com>
napisala:

**Comment by viluzi** [comment]
@sijanec Since online-mode is false if someone knows your username too, that wont work.

**Comment by sijanec** [comment]
I wanted to say that you would not use your normal username to login to the proxy server but instead a random unpredictable 16 character one. The game still works that way and i think the username is sent encrypted and not forwarded to 2b2t (because it's not your real username).

**Comment by themoonisacheese** [comment]
fixed in #83 .

**Comment by MrGeorgen** [comment]
actually it is not fixed, the online mode setting is not for the proxy server, but for the 2b2t sever. I added this, because got for login in to often for 30 minutes and one time a day. With the additional config changes I can set online mode to false and the server ip to a test server on my machine and test stuff here

**Comment by wylie39** [comment]
> actually it is not fixed, the online mode setting is not for the proxy server, but for the 2b2t sever. I added this, because got for login in to often for 30 minutes and one time a day. With the additional config changes I can set online mode to false and the server ip to a test server on my machine and test stuff here

If this hasn’t been fixed can we reopen this issue?
