### ISSUE TITLE
Error when there is no queue

### ISSUE THREAD

**Issue by HyCore** [themoonisacheese/2bored2wait#54]
Hi, i've get this error when there was no queue so i gess he couldn't detect if he was in the queue or not (by getting the number of queue the guy are) . How can we fix that ?
Anyway, you did an awsome job :) Hope you can fix that
root@user:/home/user/www-server/2bored2wait# npm start

> 2bored2wait@1.0.0 start /home/user/www-server/2bored2wait
> node main.js

end SocketClosed
Trying to reconnect
/home/user/www-server/2bored2wait/main.js:76
                        let positioninqueue = headermessage.text.split("\n")[5].substring(25);
                                                                               ^

TypeError: Cannot read property 'substring' of undefined
    at Client.client.on (/home/user/www-server/2bored2wait/main.js:76:59)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (/home/user/www-server/2bored2wait/node_modules/minecraft-protocol/src/client.js:86:12)
    at emitOne (events.js:116:13)
    at FullPacketParser.emit (events.js:211:7)
    at addChunk (/home/user/www-server/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/user/www-server/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/user/www-server/2bored2wait/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/user/www-server/2bored2wait/node_modules/readable-stream/lib/_stream_transform.js:139:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-09T09_16_02_723Z-debug.log

**Comment by AverageComet250** [comment]
Turn off is 2b2t in config.json and that should fix it.

**Comment by AverageComet250** [comment]
Now close this issue

**Comment by MrGeorgen** [comment]
it is not fixed because could be detected if there is a queue. 

> Turn off `is 2b2t` in config.json and that should fix it.

only a wokraround

**Comment by AverageComet250** [comment]
You could probably use a try and catch block and make it do what it it would do if `is2b2t` was false.

**Comment by czho** [comment]
pretty sure that themoonisacheese just patched this

**Comment by AverageComet250** [comment]
Themoonisacheese is no longer working on this and his last commit was 6 days ago

**Comment by themoonisacheese** [comment]
> 
> 
> Themoonisacheese is no longer working on this and his last commit was 6 days ago
> 
> I might fix this on my fork, but I probs won't cause I'm working on other projects atm

correct, i patched this because i had a few minutes and nothing to do and it was a quick fix. The error is due to the fact that if there is no queue, the first tab packet recieved is from the play server and not the queue server, and thus isn't of the expected format. fixed in 81f62f3.

as the comment on that commit says, there is a small possibility of my fix spamming the console, however, it would require never recieving the "now connecting" chat message which i can't see happening (after that message is recieved, 2b2w no longer tries to parse tab menu and considers the queue done).

closing because fixed.
